In [9]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
#ID: 25A = np.array([[7, 3], [10, 4]])
# 1. Size of a matrix
size_A = A.shape  # Returns dimensions (rows, columns)

# 2. Determinant of a matrix
det_A = np.linalg.det(A)



# 3. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)

# 4. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# 5. Inverse of a matrix
if np.linalg.det(A) != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Matrix is singular, cannot compute inverse"

print("Size of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

Size of A: (2, 2)
Determinant of A: -1.999999999999998
Inverse of A:
 [[-2.   1.5]
 [ 5.  -3.5]]
Rank of A: 2
Eigenvalues of A: [11.17890835 -0.17890835]
Eigenvectors of A:
 [[ 0.58317575 -0.3855776 ]
 [ 0.81234601  0.92267541]]


Changed the 1st item of row 1.
7 -> 7+1 -> 8

In [11]:
A = np.array([[8, 3], [10, 4]])
# 1. Size of a matrix
size_A = A.shape

# 2. Determinant of a matrix
det_A = np.linalg.det(A)



# 3. Rank of a matrix
rank_A = np.linalg.matrix_rank(A)

# 4. Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# 5. Inverse of a matrix
if np.linalg.det(A) != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Matrix is singular, cannot compute inverse"

print("Size of A:", size_A)
print("Determinant of A:", det_A)
print("Inverse of A:\n", inv_A)
print("Rank of A:", rank_A)

print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

Size of A: (2, 2)
Determinant of A: 2.000000000000002
Inverse of A:
 [[ 2.  -1.5]
 [-5.   4. ]]
Rank of A: 2
Eigenvalues of A: [11.83095189  0.16904811]
Eigenvectors of A:
 [[ 0.61654577 -0.35774211]
 [ 0.78731907  0.93382042]]


1. How did the determinant change and why?

The determinant went from 1.99 to 2.00

2. Did the rank change?

Rank stayed the same

3. How did the eigenvalues respond?

The eigenvalues changed but the chane was not drastic

4. Is B easier or harder to invert than A? Why?

B is easier to invert because its determinant will be bigger.