In [27]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

## 1. Scalar & Array Operations (Redo Section with Your Own Values):


In [28]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([12, 42, 11, 13.5, 16, 14.96])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [-0.53657292 -0.91652155 -0.99999021  0.80378443 -0.28790332  0.68014709]
cos: [ 0.84385396 -0.39998531  0.0044257   0.59492066 -0.95765948 -0.73307567]
tan: [  -0.63585993    2.29138799 -225.95084645    1.35107835    0.30063224
   -0.9277993 ]
asin: [0.2897517  1.57079633 0.26499533 0.32723773 0.39082613 0.36418779]
acos: [1.28104463 0.         1.305801   1.2435586  1.1799702  1.20660853]
atan: [1.48765509 1.5469913  1.48013644 1.49685729 1.50837752 1.5040507 ]
exp: [1.62754791e+05 1.73927494e+18 5.98741417e+04 7.29416370e+05
 8.88611052e+06 3.14083737e+06]
log: [2.48490665 3.73766962 2.39789527 2.60268969 2.77258872 2.70537997]
abs: [12.   42.   11.   13.5  16.   14.96]
sqrt: [3.46410162 6.4807407  3.31662479 3.67423461 4.         3.86781592]
rem: [0.   0.   1.   1.5  0.   0.96]
round: [12. 42. 11. 14. 16. 15.]
floor: [12. 42. 11. 13. 16. 14.]
ceil: [12. 42. 11. 14. 16. 15.]


## 2. 2×2 Matrix Calculations (Already Done in Class):

## 3x2 Matrix with custom values

In [29]:
# Creating a 3x2 matrix
matrix = np.array([[2.5, 7.3], [3.9, 4.6],[12.5, 16.4]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[ 2.5  7.3]
 [ 3.9  4.6]
 [12.5 16.4]]

sin:
 [[ 0.59847214  0.85043662]
 [-0.68776616 -0.993691  ]
 [-0.0663219  -0.63810668]]

cos:
 [[-0.80114362  0.52607752]
 [-0.7259323  -0.11215253]
 [ 0.99779828 -0.76994796]]

tan:
 [[-0.7470223   1.61656142]
 [ 0.94742465  8.8601749 ]
 [-0.06646824  0.82876599]]

asine:
 [[0.15303567 0.46131044]
 [0.24010527 0.28430228]
 [0.86669733 1.57079633]]

acosine:
 [[1.41776065 1.10948588]
 [1.33069106 1.28649405]
 [0.704099   0.        ]]

atangent:
 [[1.19028995 1.43465737]
 [1.31979364 1.35673564]
 [1.49096634 1.50989612]]

exp:
 [[1.21824940e+01 1.48029993e+03]
 [4.94024491e+01 9.94843156e+01]
 [2.68337287e+05 1.32565191e+07]]

log (natural):
 [[0.91629073 1.98787435]
 [1.36097655 1.5260563 ]
 [2.52572864 2.79728133]]

abs:
 [[ 2.5  7.3]
 [ 3.9  4.6]
 [12.5 16.4]]

sqrt:
 [[1.58113883 2.70185122]
 [1.97484177 2.14476106]
 [3.53553391 4.04969135]]

rem (remainder when divided by 2):
 [[0.5 1.3]
 [1.9 0.6]
 [0.5 0.4]]

round:
 [[ 2.  7.]
 [

## Task: Perform Same Operations on a 2×3 Matrix that has float values

In [30]:
# 2x3 matrix
vec = np.array([[2.5, 4.5, 9.5], [2.1, 7.57, 8.88]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.unravel_index(np.argmax(vec), vec.shape)

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.unravel_index(np.argmin(vec), vec.shape)

# 3. Length of the vector
vec_length = vec.size

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)

## more sorting
sorted_entire = np.sort(vec, axis=None)[::-1]  # Entire matrix descending
sorted_rows = np.sort(vec, axis=1)[:, ::-1]  # Row-wise descending


# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("\nSorted row-wise (descending):\n", sorted_rows)
print("\nSum of elements:", sum_values)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 9.5 at index (np.int64(0), np.int64(2))
Min value: 2.1 at index (np.int64(1), np.int64(0))
Length of vector: 6
Sorted vector: [[2.5  4.5  9.5 ]
 [2.1  7.57 8.88]]

Sorted row-wise (descending):
 [[9.5  4.5  2.5 ]
 [8.88 7.57 2.1 ]]

Sum of elements: 35.050000000000004
Sum of elements: 35.050000000000004
Product of elements: 15087.047850000003
Median value: 6.035
Mean value: 5.841666666666668
Standard deviation: 2.9599798235048085


##